version: '3.8'

services:
  flask-stats:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: server-stats-flask
    env_file:
      - ./app/.env
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/var/log/server-stats
    tty: true
    stdin_open: true
