Name: CI for server-stats.sh

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Run ShellCheck (lint shell scripts)
       uses: ludeeus/action-shellcheck@v2
       with:
         check_paths: server-stats.sh

     - name: Build Docker Image
       run: docker build -t server-stats .

     - name: Push Docker image
       if: github.event_name == 'push'
       run: |
          docker tag server-stats docker.io/${{ secrets.DOCKER_USERNAME }}/server-stats:latest
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/server-stats:latest
       
      
